"""Widget dimension constants (heights, widths, fixed sizes) shared across the UI."""

# Square icon buttons (edit/delete actions in list rows)
ICON_BUTTON_SIZE = 36

# Input fields
INPUT_HEIGHT = 30
INPUT_HEIGHT_COMPACT = 24
INPUT_HEIGHT_LARGE = 40
CART_LABEL_HEIGHT = 20
NUMPAD_KEY_HEIGHT = 48

# Buttons
BUTTON_HEIGHT = 40
BUTTON_HEIGHT_SM = 44
BUTTON_HEIGHT_XS = 26
BUTTON_HEIGHT_COMPACT = 36
BUTTON_HEIGHT_LG = 50
BUTTON_HEIGHT_XL = 54

# Table row heights
ROW_HEIGHT_COMPACT = 30
ROW_HEIGHT = 44
ROW_HEIGHT_LARGE = 50

# Main window chrome
MAIN_WINDOW_MIN_WIDTH = 1366
MAIN_WINDOW_MIN_HEIGHT = 768
HEADER_MIN_HEIGHT = 50
HEADER_MAX_HEIGHT = 70
TAB_BAR_MIN_HEIGHT = 44
TAB_BAR_MAX_HEIGHT = 56

# Dialog widths
DIALOG_WIDTH_SM = 300
DIALOG_WIDTH_MD = 400
DIALOG_WIDTH_LG = 420
DIALOG_WIDTH_XL = 480

# Misc field/panel sizes
FIELD_WIDTH_SM = 100
FIELD_WIDTH_MD = 120
LIST_PANEL_MIN_WIDTH = 360
LIST_PANEL_MAX_WIDTH = 520
LOGO_PREVIEW_SIZE = (120, 60)

__all__ = [
    "ICON_BUTTON_SIZE",
    "INPUT_HEIGHT",
    "INPUT_HEIGHT_COMPACT",
    "INPUT_HEIGHT_LARGE",
    "CART_LABEL_HEIGHT",
    "NUMPAD_KEY_HEIGHT",
    "BUTTON_HEIGHT",
    "BUTTON_HEIGHT_SM",
    "BUTTON_HEIGHT_XS",
    "BUTTON_HEIGHT_COMPACT",
    "BUTTON_HEIGHT_LG",
    "BUTTON_HEIGHT_XL",
    "ROW_HEIGHT_COMPACT",
    "ROW_HEIGHT",
    "ROW_HEIGHT_LARGE",
    "MAIN_WINDOW_MIN_WIDTH",
    "MAIN_WINDOW_MIN_HEIGHT",
    "HEADER_MIN_HEIGHT",
    "HEADER_MAX_HEIGHT",
    "TAB_BAR_MIN_HEIGHT",
    "TAB_BAR_MAX_HEIGHT",
    "DIALOG_WIDTH_SM",
    "DIALOG_WIDTH_MD",
    "DIALOG_WIDTH_LG",
    "DIALOG_WIDTH_XL",
    "FIELD_WIDTH_SM",
    "FIELD_WIDTH_MD",
    "LIST_PANEL_MIN_WIDTH",
    "LIST_PANEL_MAX_WIDTH",
    "LOGO_PREVIEW_SIZE",
]
